spring:
  profiles:
    active: first
    
#spring:
#  application:
#    name: itcast-microservice-eureka #指定服务名
#server:
#  port: 8091 #服务端口
#
#
#eureka:
#  client:
#    registerWithEureka: false #是否将自己注册到Eureka服务中，本身就是所有无需注册
#    fetchRegistry: false #是否从Eureka中获取注册信息
#    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
#      defaultZone: ${eureka.server}
#  instance:
#    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
#    ip-address: 127.0.0.1
#    instance-id: itcast-microservice-eureka:8090 #指定实例id
#  server:
#    enable-self-preservation: false #禁用自我保护模式
#    eviction-interval-timer-in-ms: 60000 #清理间隔（单位毫秒，默认是60*1000）

#logging:
#  level:
#    root: debug
##    org.springframework.web: DEBUG
#  file: /log/log/my_eureka.log
#  pattern:
#    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
#    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
#logging.level.root=WARN        